### ISSUE TITLE
Hinzufuegen von Item Heiltrank klein & groß

### ISSUE THREAD

**Issue by ScorpionProg** [ScorpionProgramming/Die-Welt-von-Zuul#1]
Heiltrank klein soll den Spieler einmal heilen
Heiltrank groß soll den Spieler zweimal heilen

**Comment by ghost** [comment]
Sollte Zaubetrank eine eigene Klasse sein und davon klein und gross erben? 
Oder einfach durch eine Variable entscheiden ob es klein oder gross ist?

Ich persönlich finde die erste Option besser, da wir in diesen Fall die möglichkeit hätten, mehrere Zaubetränke hinzuzufügen.

**Comment by ScorpionProg** [comment]
Ich würde es als eigene Klasse machen. Aber nur wegen der Erweiterbarkeit der eigenständigen Klasse.

Zum Beispiel kann man dann entscheiden ob man aus dem Zaubertrank mehrmals Trinken kann je nach größe

**Comment by ScorpionProg** [comment]
Ich hab ne Plan Änderungen zu sagen, wir machen das Prinzip des heilen in der Klasse spiel und dann machen wir einfach nen Heiltrank als Gegenstand

**Comment by ScorpionProg** [comment]
nur kleiner Heiltrank hinzugefuegt - done -
