### ISSUE TITLE
Neuen Befehl 'use' hinzufuegen

### ISSUE THREAD

**Issue by ScorpionProg** [ScorpionProgramming/Die-Welt-von-Zuul#2]
Es soll ein neuer Befehl 'use' hinzugefuegt werden um die Karte oder die Zaubertraenke zu benutzen

**Comment by ghost** [comment]
Befehl wurde schon hinzugefuegt. Muss noch die Zaubertraenke implementiert werden.

**Comment by ScorpionProg** [comment]
done
