### ISSUE TITLE
Raumgenerator als eigene Klasse 

### ISSUE THREAD

**Issue by ScorpionProg** [ScorpionProgramming/Die-Welt-von-Zuul#3]
Es soll eine neue Klasse erstellt werden um die Klasse Landkarte nur für das halten und ausgeben der Weltkarte zu erstellen. 
Die Klasse LevelGenerator oder Raumgenerator uebernimmt dann die Arbeit die Raeume zu erstellen und sie mit Monstern und Gegenstaenden zu befuellen.

**Comment by ScorpionProgramming** [comment]
done!

**Comment by ScorpionProg** [comment]
done
