### ISSUE TITLE
Möglichkeit zu gewinnen/beenden

### ISSUE THREAD

**Issue by ghost** [ScorpionProgramming/Die-Welt-von-Zuul#5]
Der Spieler sollte die Möglichkeit bekommen, gewinnen zu können. Entweder beim Besiegen aller Monster oder beim Finden eines Ausganges oder eines bestimmten Gegenstandes.

Was denkt ihr davon?

**Comment by ScorpionProg** [comment]
Gute Idee, machen wir!

**Comment by ScorpionProg** [comment]
done
